# Generated by Django 5.1.15 on 2026-06-13 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(blank=True, help_text='e.g. Holiday, Rest day, Already full', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_time', models.TimeField(blank=True, help_text='What time the event starts', null=True)),
                ('setup_time', models.TimeField(blank=True, help_text='What time we need to arrive for setup', null=True)),
                ('venue', models.TextField(blank=True, help_text='Full venue address')),
                ('venue_lat', models.CharField(blank=True, max_length=30)),
                ('venue_lng', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('pkg_type', models.CharField(choices=[('froyo', 'Frozen Yogurt & Soft Serve'), ('taiyaki', 'Koi Taiyaki')], default='froyo', max_length=20)),
                ('pkg_name', models.CharField(max_length=100)),
                ('pkg_price', models.CharField(max_length=30)),
                ('sauces', models.CharField(blank=True, max_length=500)),
                ('crunches', models.CharField(blank=True, max_length=500)),
                ('fruits', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('payment_notes', models.TextField(blank=True, help_text='Internal payment tracking notes')),
                ('payment_received', models.BooleanField(default=False, help_text='Has payment been received?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_booking', 'New Booking'), ('new_review', 'New Review'), ('status', 'Status Update')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('event_type', models.CharField(blank=True, choices=[('Wedding', 'Wedding'), ('Birthday Party', 'Birthday Party'), ('Debut', 'Debut'), ('Corporate Event', 'Corporate Event'), ('School Event', 'School Event'), ('Market / Pop-up', 'Market / Pop-up'), ('Other', 'Other')], max_length=100)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='landing.booking')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
